### PR TITLE
Add marketing email in form

### PR DESCRIPTION
**Pull request by amalbas**
### **Description**
Add marketing email checkbox on register page and add translations. Changes for site configurations:
To see the field in lms:
 "REGISTRATION_EXTRA_FIELDS": {
  "allow_marketing_emails":"optional"
}
To save data in meta field:
 "extended_profile_fields": [
     "allow_marketing_emails"
  ]

@itsjeyd 
@clemente 
@pomegranited

### CODE REVIEW

**Comment by clemente** [comment]
@amalbas Thanks! I'll review it this week. CC @itsjeyd 

> To save data in meta field:

How should we test it? How do you see this UserProfile.meta field? Maybe from a theme, or from some export?

**Comment by amalbas** [comment]
@clemente To test it, you should make the registration process for a new user, and you could see meta field in the user information in admin, USER PROFILE section.

**Comment by clemente** [comment]
@amalbas Some comments, before testing it.

**Upstreaming**
- the main concern is how this will be upstreamed, in a way that will be accepted by edX. This is important because we need to make the upgrades easier, so we need to reduce and avoid the additions to the platform that aren't upstreamed (accepted by edX). Did you already prepare how to upstream this change?
- this code is modifying the internal classes of edx-platform. It seems there's a better way to change the fields in the registration form, that wouldn't require modifying the core: [REGISTRATION_EXTENSION_FORM](https://github.com/edx/edx-platform/blob/803db4ee3ff0bdbc388d52d5285d24a3b1b4b588/lms/envs/common.py#L3080), which allows you to use another class (defined in an external Django app that is not in the core), and it can be saved in the BD if needed. This extensibility is already supported and nothing would need to be upstreamed, and it wouldn't create much more work in upgrades. I have seen examples of the registration form extensions and it can be very simple: a `forms.py` with `class ExtraInfoForm(ModelForm)` and a `models.py` with `class ExtraInfo(models.Model)` with the extra field (like `models.BooleanField`). Could you add to the PR whether you considered this approach (registration form extensions) and why wouldn't it work?
- (by the way, Campus has `ENABLE_COMBINED_LOGIN_REGISTRATION: true`, which is required by REGISTRATION_EXTENSION_FORM)

**Translations**
The translations are changing too much of the file. The `django.po` differs in size by more than 120 Kb and the diff is huge (1'9 Mb just for Hebrew). Many strings are being commented out (the 2nd half of the file, line 10575 onwards, is just deleting translations). For instance (random example) `"View Certificate"` is being removed and it doesn't seem right because the string is still used by `lms/templates/courseware/progress.html`.
Looking at the repository history I see that the previous translation updates haven't been so large. If you continue this same approach, could you try to redo the translation? Ideally, it should add only the new strings that you're adding.
If you do the registration form extension, I guess that the new strings can be independently in the new application.

Maybe you used a newer version of the platform to compile the changes? Ideally it can be done in the Campus devstack. Last time I had to update translations, I could do some of the steps outside the Campus devstack, but I don't know know whether it's possible for this change.

**Comment by clemente** [comment]
@amalbas By the way, some news about translations: it looks like even in our current Campus branch, the translations haven't  been pulled from Transifex in a long time, and there are many errors and conflicts when trying to do it.
We have seen it happen recently with other changes.
So a simpler solution is to manually choose the translations you want. For instance, you can pull all Transifex translations, find the ones that you need, and commit only those lines. It's very manual but it may be better than the alternative…

**Comment by amalbas** [comment]
@clemente 
About upstreaming comment, we usually use the extension form but according to the documentation that Roi gave us https://docs.google.com/document/d/1drANe_6DY4OV0f69OWuwWmr41gFtHFQ8-qerSUoaSRM, they wanted to add this field using the list of extender_profile_filed and save the data in meta field and to do that it's necessary the change in the platform. 

For the translations, you're right, it's taking the changes from a new version so I'm working on that and it'll be updated soon.

**Comment by clemente** [comment]
@amalbas The translations are much clearer now, thanks.

As for upstreaming: we'd still need a way to upstream this, otherwise we're adding code drift that we need to maintain and port. The preferred approach would be:
1. develop a PR to upstream (edx) (master branch)
2. have it accepted and merged upstream
3. after it's merged, backport it to Campus branches

To be able to add the current solution upstream, it would have to be behind a flag so that the new field doesn't appear on all instances.
Could you prepare a plan to upstream the feature? I'll also discuss it in the CAM2 ticket, since this process may be slow.

**Comment by clemente** [comment]
We ended up using https://github.com/edx-olive/custom-registration-form, which is much simpler, it doesn't require changes to edx-platform, and the translations are easier to control. I tested it on stage and it works well, so :+1: to that one, @amalbas 
I'll close this one.

**Comment by itsjeyd** [comment]
@amalbas Thanks for changing the approach here :)

**Pull request closed without merging**
