### PR TITLE
[SE-2506][CAM2-328] Fix forum image upload

### PR DESCRIPTION
**Pull request by pkulkark**
This PR modifies the current forum image upload flow. The image was being uploaded to the configured storage when the user selected a file from the file picker without waiting for confirmation. The upload method will now be called only once the user clicks 'OK' button confirming the selection. 

**Testing Instructions:**
1. Go to a forum dicussion page in a course and click on 'Add a Post'.
2. In the editor, click on image icon and click 'Choose File' button to open file picker.
3. Select an image file you want to upload.
4. Verify the file name is shown in the text area. Provide a description for the image or enable flag indicating image is decorative only.
5. Click OK. Verify the upload api is called only after OK is clicked and the image is rendered in preview.

**Reviewers:**

- [x] @swalladge 

**Authors notes and concerns:**
1. The image will need to be uploaded before the entire post is submitted since the editor tries to generate the preview. So this still wouldn't handle the case where user uploads the image and then discards the post.
2. I couldn't find a better way other than introduce a wait time of 0.1sec after the user clicks 'OK' as we need to wait for the upload to complete before rendering the preview.

### CODE REVIEW

**Comment by swalladge** [comment]
@pkulkark :+1: with nit: I think we need to avoid using a timeout here.

> I couldn't find a better way other than introduce a wait time of 0.1sec after the user clicks 'OK' as we need to wait for the upload to complete before rendering the preview.

Can we wait for the imageUploadHandler to complete before calling `close`? I took a quick glance and it appears to be some kind of async object. The issue I can think of is that if this is async, and the network is slow, then it will attempt to close and save before the url input is populated with the uploaded image url, so it will crash.

- [x] I tested this: followed test instructions
- [x] I read through the code
- [x] I checked for accessibility issues
- [x] Includes documentation
- [ ] NA I made sure any change in configuration variables is reflected in the corresponding
    client's `configuration-secure` repository.

**Comment by pkulkark** [comment]
@swalladge 
> Can we wait for the imageUploadHandler to complete before calling close?

I wasn't able to find a way to do that. I tried using `$.when(imageUploadHandler(fileInput, urlInput)).done(() => { return close(false); })`  and `imageUploadHandler(fileInput, urlInput).then(() => { return close(false); })` but none of them worked. It would just return before the async call completed. I don't know if I'm missing something there (my js knowledge is quite limited and edX seem to have written a lot of custom code for this).

**Comment by swalladge** [comment]
> Do you have any suggestions?

@pkulkark None other than what you already tried sorry.

**Comment by pkulkark** [comment]
@swalladge Ok I'll go ahead and deploy this on stage so that you can do a final check before merging.  And i'll make a note on the ticket about the concern.

**Pull request merged**
