### PR TITLE
SE-3494 Revert "hide ccx courses from catalog"

### PR DESCRIPTION
**Pull request by swalladge**
This reverts commit b44713f2957d68dac257fcb99984d27164a74bf2.

This is no longer required for client, and by reverting this, we reduce
code drift from upstream.

**Test instructions**:

- verify that this reverts https://github.com/edx-olive/edx-platform/pull/6 exactly
- deploy to stage and do some spot checks viewing courses you do and don't have access to (the code change was minor and clean, so it should be fine)

**Reviewers**:

- [x] @Kelketek

### CODE REVIEW

**Comment by Kelketek** [comment]
@swalladge This PR looks good to me-- I can't find any other uses of that function you've removed and the revert appears quite clean. However I've noticed the build is failing. Do we know anything about that? It doesn't appear to be obviously related to your change, so if it's something we already know about, 👍 Otherwise please look into it and if we're confident it's not some weird unrelated issue, please create a ticket for it to follow up.

I couldn't follow your AMI link (I don't have access, looks like). But this is good to go to stage.

:+1:

- [ ] ~~I tested this: (describe what you tested)~~
- [X] I read through the code
- [ ] ~~I checked for accessibility issues~~
- [ ] ~~Includes documentation~~
- [ ] ~~I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.~~

**Comment by swalladge** [comment]
Thanks @Kelketek 

> However I've noticed the build is failing. Do we know anything about that?

Yeah the tests are failing everywhere on this fork; we haven't had time or inclination to look into them unfortunately.

**Comment by Kelketek** [comment]
@swalladge If that's the case I see little reason not to go ahead and merge. Do we have a ticket in for it already? Please create one if not.

**Comment by itsjeyd** [comment]
@Kelketek @swalladge You might have already checked but we have [SE-1986](https://tasks.opencraft.com/browse/SE-1986) for addressing the failing tests, so no need to create an additional ticket.

**Pull request merged**
