### PR TITLE
[SE-4027] revert grading policy updates

### PR DESCRIPTION
**Pull request by gabor-boros**
Reverts the grading policy related updates as requested by Campus.

**Dependencies**: None

**Screenshots**: 

Screenshot 2021-03-09 at 14 50 45

**Sandbox URL**: N/A

**Merge deadline**: None

**Testing instructions**:

1. Pull the changes
2. Start devstack / restart webservers
3. Create a new course
4. Navigate to gradings
5. Validate no changes present which are related to https://github.com/edx-olive-oc/edx-platform/pull/9 and https://github.com/edx-olive-oc/edx-platform/pull/16

**Author notes and concerns**:

1. I tested the site locally (checked grading), and checked what was reverted, I'm not 100% confident that we won't break something with these changes, since the tests are failing (on any change/any PR).
2. Although I wasn't able to run the commands below - failing because of syntax error in a 3rd party package -, I did revert the changes within the `djangojs.js` files to mitigate the issue.

* run `./manage.py lms --settings openstack compilejsi18n`
* run `./manage.py cms --settings openstack compilejsi18n`

**Reviewers**
- [ ] @nizarmah

### CODE REVIEW

**Review by nizarmah — CHANGES_REQUESTED** [review]
## Review Criteria 

### [CAM2-3 Adding Grading Policy validation #9 tests](https://github.com/edx-olive-oc/edx-platform/pull/9#pullrequestreview-150428008)

- [x] The `Actual Number` field **is not displayed**
image
- [x] Editing `Weight of Total Grade` to make the total != 100 **does not show** the `Total weight must be 100%.` error message
- [x] Saving the changes **does not show** the `Assignment types weight summary` modal dialog.

### [Update translated LMS djangojs.js files #16 !tests]()

> This issue is difficult to test in the devstack because the issue doesn't occur in development; it only occurs in production when the static asset pipeline is in use.
> 
> But you can verify the conditions by running these steps, and ensuring that no changes are made on this branch:
> ```
> ./manage.py lms --settings openstack compilemessages
> ./manage.py lms --settings openstack compilejsi18n
> ./manage.py cms --settings openstack compilejsi18n
> ```

I had some trouble verifying this, and I suspect it's one of the issues with my devstack 🤦🏼 

The only step that ran for me was the `compilemessages`. It didn't generate any new files.
But could you please run this and let me know if it works for you and if it doesn't generate any changes?

---

- [ ] I read through the code.
I didn't, yet, because the code changes that were created were `git revert <commit hash>`

---

By the way,  I was comparing the [`lib_unit_tests`](https://app.circleci.com/pipelines/github/edx-olive/edx-platform/173/workflows/5f95a68d-1874-4328-923c-c403574cff9d/jobs/928) and the [`lms_unit_tests`](https://app.circleci.com/pipelines/github/edx-olive/edx-platform/173/workflows/5f95a68d-1874-4328-923c-c403574cff9d/jobs/927) with the ones from the [`pooja/cherry-pick-pymongo-upgrade:lib_unit_tests`](https://app.circleci.com/pipelines/github/edx-olive/edx-platform/171/workflows/9a31e2a9-c8c6-4309-99e5-242d440f3b21/jobs/920) and [`pooja/cherry-pick-pymongo-upgrade:lms_unit_tests`](https://app.circleci.com/pipelines/github/edx-olive/edx-platform/171/workflows/9a31e2a9-c8c6-4309-99e5-242d440f3b21/jobs/918). 

Would you please mind adding a list of the new failed tests in a comment?
Also would you mind please attempting to fix them? Just so we make sure that the new failed tests won't result in any failed functionality on the platform.

**Comment by itsjeyd** [comment]
@nizarmah @gabor-boros 

> By the way,  I was comparing the [`lib_unit_tests`](https://app.circleci.com/pipelines/github/edx-olive/edx-platform/173/workflows/5f95a68d-1874-4328-923c-c403574cff9d/jobs/928) and the [`lms_unit_tests`](https://app.circleci.com/pipelines/github/edx-olive/edx-platform/173/workflows/5f95a68d-1874-4328-923c-c403574cff9d/jobs/927) with the ones from the [`pooja/cherry-pick-pymongo-upgrade:lib_unit_tests`](https://app.circleci.com/pipelines/github/edx-olive/edx-platform/171/workflows/9a31e2a9-c8c6-4309-99e5-242d440f3b21/jobs/920) and [`pooja/cherry-pick-pymongo-upgrade:lms_unit_tests`](https://app.circleci.com/pipelines/github/edx-olive/edx-platform/171/workflows/9a31e2a9-c8c6-4309-99e5-242d440f3b21/jobs/918). 
> Would you please mind adding a list of the new failed tests in a comment?
> Also would you mind please attempting to fix them? ...

Before spending time working on potential fixes, please confirm for each new failure whether it is directly related to the changes from this PR. We've seen some flakiness over time with these tests (and no end user impact), and there is a separate ticket for fixing them, [SE-1986](https://tasks.opencraft.com/browse/SE-1986). So fixing any failures that can't be linked directly to changes from this PR is out of scope here.

**Comment by gabor-boros** [comment]
@nizarmah

> The only step that ran for me was the compilemessages. It didn't generate any new files.
But could you please run this and let me know if it works for you and if it doesn't generate any changes?

As I wrote in the description, I wasn't able to run those commands (ie. `compilejsi18n`) either, because of a 3rd party package's error but reverted the changes:

> Although I wasn't able to run the commands below - failing because of syntax error in a 3rd party package -, I did revert the changes within the djangojs.js files to mitigate the issue.

Regarding translations (in this case) the worst case would be that we have more translations than needed (but since I removed them manually, it shouldn't be an issue anymore).

---

> By the way, I was comparing the lib_unit_tests and the lms_unit_tests with [...]

@nizarmah The lib_unit_tests failure (1 failure) is the same (`AssertionError: 'colorsys' unexpectedly found in [...]`) - no new failures were introduced.  In case of lms_unit_tests failure is really hard to know what is the difference:

Previously (on Pooja's branch):
```
FAILED (SKIP=77, errors=266, failures=29)
```

On this branch:
```
FAILED (SKIP=77, errors=219, failures=29)
```

As you can see we "fixed" some tests (or not?). The tests are flaky which means that if I parse the output of the CI job and compare the results that will probably lead to a false-positive or false-negative result but not a correct one.

Would you still like me to spend time on producing the comparison (don't take me wrong, I'm doing it happily though I think the given value is questionable).

cc: @itsjeyd

**Review by nizarmah — APPROVED** [review]
@gabor-boros 

> Regarding translations (in this case) the worst case would be that we have more translations than needed (but since I removed them manually, it shouldn't be an issue anymore).

Alright, thanks for clarifying that! 

---

I can't believe I managed to link the tests correctly, but managed to confuse them in my comparison... 🤦🏼 

> Would you still like me to spend time on producing the comparison (don't take me wrong, I'm doing it happily though I think the given value is questionable).

No, I'm glad you mentioned what you did, that's a big human error on my end! Sorry about that!

Approving the pull request 👍🏼

**Comment by gabor-boros** [comment]
@nizarmah No issues at all! It happens time to time with me either :D

**Pull request merged**
