### PR TITLE
[SE-3236] Apply XSS patches

### PR DESCRIPTION
**Pull request by toxinu**
This pull request is about backporting XSS fixes from [BB-2941](https://tasks.opencraft.com/browse/BB-2941).

**Jira tickets**

- [SE-3236](https://tasks.opencraft.com/browse/SE-3236)
- [BB-2941](https://tasks.opencraft.com/browse/BB-2941)

**Testing instructions**

TBA

**Reviewers**

TBA

### CODE REVIEW

**Comment by clemente** [comment]
@toxinu The branch that Campus is working with (even in production) is https://github.com/edx-olive/edx-platform/tree/pooja/cherry-pick-pymongo-upgrade , could you change your target branch? See https://github.com/edx-olive/edx-platform/pull/31 for reference.

**Comment by toxinu** [comment]
@clemente I changed the target branch 👍🏻

**Comment by pkulkark** [comment]
@toxinu I deployed this on stage and did some sanity checks. LGTM :+1: 

- [x] I tested this: did some sanity checks around the changes included in this PR
- [x] I read through the code
- [ ] ~~Checked for accessibility~~ N/A
- [ ] ~~Includes documentation~~ N/A

**Review by pkulkark — APPROVED** [review]

**Comment by toxinu** [comment]
Thanks @pkulkark! 😃

**Pull request merged**
